-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE blog (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author text,
    type text,
    date text,
    content text,
    createtime timestamp with time zone DEFAULT now(),
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX blog_pkey ON blog(id int4_ops);


-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    password text NOT NULL,
    timezone_gap smallint NOT NULL DEFAULT '0',
    createtime timestamp with time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_pkey ON users(id int4_ops);
